# Generated by Django 4.2 on 2024-09-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_aduit_type(apps, schema_editor):
    DashboardLink = apps.get_model('riskmanagement', "AuditType")

    initial_data = [
        {
            'department': 'collections', 
            'name': "State Dialing", 
            'risk_level': 2, 
            'testing_frequency': 7, 
            'passing_score': 100,
        },
        {
            'department': 'collections', 
            'name': "Calls Per Week", 
            'risk_level': 2, 
            'testing_frequency': 7, 
            'passing_score': 100,
        },
    ]

    for data in initial_data:
        DashboardLink.objects.create(**data)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagementPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_risk_management', 'Can access the Risk Management section')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(choices=[(0, 'Business'), (1, 'Collections'), (2, 'REM'), (3, 'AnotherBank'), (4, 'AClient'), (5, 'InsuranceComp'), (6, 'Bank'), (7, 'AStore'), (8, 'Finance'), (9, 'Clothes'), (10, 'The Bank')], default=0)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('date_ran', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eval_start_date', models.DateField(null=True)),
                ('eval_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('posting', 'Posting'), ('performance', 'Performance'), ('information technology', 'Information Technology '), ('human resources', 'Human Resources'), ('compliance', 'Compliance'), ('collections', 'Collections'), ('accounting', 'Accounting')])),
                ('name', models.CharField(max_length=255)),
                ('risk_level', models.IntegerField(choices=[(2, 'High'), (3, 'Medium'), (5, 'Low')])),
                ('testing_frequency', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (14, 'Bi-Weekly'), (30, 'Monthly'), (60, 'Bi-Monthly'), (90, 'Quartlery'), (180, 'Bi-Annually'), (356, 'Annually')])),
                ('passing_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CallsPerWeekAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_evaluated', models.IntegerField(null=True)),
                ('unique_calls_evaluated', models.IntegerField(null=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.audit')),
            ],
        ),
        migrations.CreateModel(
            name='StateDialingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_evaluated', models.IntegerField(null=True)),
                ('unique_calls_evaluated', models.IntegerField(null=True)),
                ('fdcpa_early', models.IntegerField(null=True)),
                ('fdcpa_Late', models.IntegerField(null=True)),
                ('michigan_early', models.IntegerField(null=True)),
                ('oklahoma_early', models.IntegerField(null=True)),
                ('oregon_early', models.IntegerField(null=True)),
                ('texas_early', models.IntegerField(null=True)),
                ('texas_sunday', models.IntegerField(null=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.audit')),
            ],
        ),
        migrations.CreateModel(
            name='CallsPerWeekReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubs_account_number', models.IntegerField()),
                ('call_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contact_tally', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('calls_per_week_audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.callsperweekaudit')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_identified', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'In Progress')])),
                ('description', models.TextField()),
                ('recommendations', models.TextField()),
                ('actions_taken', models.TextField()),
                ('documentation', models.FileField(blank=True, null=True, upload_to='audit_documents')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.audit')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.audittype'),
        ),
        migrations.AddField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_aduit_type),
    ]
