# Generated by Django 4.2 on 2024-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_operations', 'Can access the Operations section')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productvity_file_title', models.CharField(max_length=255)),
                ('productivity_uploaded_file', models.FileField(upload_to='uploads/')),
                ('calls_file_title', models.CharField(max_length=255)),
                ('calls_uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayForPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayForPerformanceEmployee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_name_and_suffix', models.CharField()),
                ('first_name', models.CharField()),
                ('most_recent_hire_date', models.DateField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=20)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
